### PR TITLE
Lab 1

### PR DESCRIPTION
**Pull request by samuelcheung924**
testing

### CODE REVIEW

**Comment by einbahnstrasse** [comment]
Hi Samuel — Thanks for submitting a pull request! Just in case it's unclear, you only need to "commit" your changes for Lab #1 in order to submit it. (No need to submit a pull request). We'll actually do pull requests later as part of another lab... Cheers!

**Comment by cuba41** [comment]
Good Afternoon Professor, I’m not sure exactly if the previous email you sent me was meant for me because you mention Samuel and not me. I’m not sure if you sent it to me by mistake or if there was something I doing incorrectly. I apologize if I reply late since I’m at work right now but, I’ll get back to you the best I can.

Thank you Antonio Almaguer
________________________________

**Comment by einbahnstrasse** [comment]
Hi Antonio — No this was meant for Samuel. Interesting you got a notification about this, though. It appears you've gotten an email about this because you're "watching" this project on Github (see the "Watch" or "Unwatch" button towards the top of your screen on Github, i.e. when you're on the page that this comment appears on). Maybe you hit the "watch" button by mistake, but depending on your preferences this means you'll see notifications about updates, comments, issues, and pull requests like this. There's no need to follow the project on Github; you might want to simply select "unwatch" if it might be confusing, but feel free to keep "watching" the project if you'd like.

**Comment by samuelcheung924** [comment]
Hello,

I have completed the two lab homeworks.  Would you check?

Also, instead of using my gmail, may we do the email communications using
my school email?  Samuel.Cheung@mail.citytech.cuny.edu

My gmail just have a lot of junks which is so distracting sometimes ; )

Samuel

**Comment by einbahnstrasse** [comment]
Hi Samuel — I checked and it looks like you've successfully completed & submitted the labs! 

The only reason you're continuing to get email on this thread is because you submitted the pull request, which I've since closed, and it's also likely that your personal email is linked to your Github account. You can put your City Tech email on Github if you'd prefer that. 

No worries; we'll be using our City Tech email accounts & Slack for our course communication — not Github.

**Comment by samuelcheung924** [comment]
Sure.  Thank you very much!

**Pull request closed without merging**
